### ISSUE TITLE
Mod Request  Fast Leaf decay

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#11]
just a mod which i always think is handy, i have also noticed it has less impact on performance than in 1.7

**Comment by robaimes** [comment]
Was looking to put this in. It used to be part of Random Things, but apparently no longer.

I will add this in at some point, but hoping I can get a treecapitator style mod too.

**Comment by trechetican** [comment]
i found this mod not sure how stable it is but https://minecraft.curseforge.com/projects/lumberjack

**Comment by robaimes** [comment]
I would want to use something that allows for almost any axe, not just a specific item unfortunately.

**Comment by trechetican** [comment]
aye fair enough. just looking through same mods soooooooo. there is just vein miner https://minecraft.curseforge.com/projects/veinminer

**Comment by Yandols** [comment]
Would recommend this one https://minecraft.curseforge.com/projects/fastleafdecay for a Fast Leaf Decay mod, its the one ive been using and seems to be compatible with most modded trees.

**Comment by robaimes** [comment]
[Fast Leaf Decay](https://minecraft.curseforge.com/projects/fast-leaf-decay?gameCategorySlug=mc-mods&projectID=225839) has been added.

**Comment by robaimes** [comment]
As an addon to this, VeinMiner has now been added, but configured to work on **_only**_ trees.
