### ISSUE TITLE
Mod Requests!

### ISSUE THREAD

**Issue by Sataana** [DNSTechpack/DNS10-MC1.10.2#12]
AppleSkin - https://github.com/squeek502/AppleSkin/releases - https://github.com/squeek502/AppleSkin/releases/download/v1.0.1/AppleSkin-mc1.10.2-1.0.1.jar

Thut's Elevators - https://mods.curse.com/mc-mods/minecraft/224375-thuts-elevators - https://minecraft.curseforge.com/projects/thuts-elevators/files/2320143/download

FFS - Fancy Fluid Storage - https://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage - https://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage/files/2311053/download

FloodLights - https://minecraft.curseforge.com/projects/floodlights - https://minecraft.curseforge.com/projects/floodlights/files/2316254/download

HelpFixer - https://mods.curse.com/mc-mods/minecraft/223797-helpfixer - https://minecraft.curseforge.com/projects/helpfixer/files/2320763/download

ChaoticKarma - https://minecraft.curseforge.com/projects/chaotickarma/files - https://minecraft.curseforge.com/projects/chaotickarma/files/2319203/download

ChanceCubes - https://minecraft.curseforge.com/projects/chance-cubes/files - https://minecraft.curseforge.com/projects/chance-cubes/files/2322515/download

Ender Utilities - https://minecraft.curseforge.com/projects/ender-utilities - https://minecraft.curseforge.com/projects/ender-utilities/files/2318591/download

Ender Zoo - https://minecraft.curseforge.com/projects/ender-zoo - https://minecraft.curseforge.com/projects/ender-zoo/files/2312494/download

EnergySynergy - https://minecraft.curseforge.com/projects/energysynergy - https://minecraft.curseforge.com/projects/energysynergy/files/2313225/download

Cyclops Core - https://minecraft.curseforge.com/projects/cyclops-core - https://minecraft.curseforge.com/projects/cyclops-core/files/2322376/download

EZStorage 2 - https://minecraft.curseforge.com/projects/ezstorage-2 - https://minecraft.curseforge.com/projects/ezstorage-2/files/2320453/download

FluidConverters - https://minecraft.curseforge.com/projects/fluidconverters - https://minecraft.curseforge.com/projects/fluidconverters/files/2312916/download

Funnels - https://minecraft.curseforge.com/projects/funnels - https://minecraft.curseforge.com/projects/funnels/files/2313514/download

SimpleHarvest - https://minecraft.curseforge.com/projects/simpleharvest - https://minecraft.curseforge.com/projects/simpleharvest/files/2321892/download

Integrated Dynamics - https://minecraft.curseforge.com/projects/integrated-dynamics - https://minecraft.curseforge.com/projects/integrated-dynamics/files/2319263/download

Common Capabilities - https://minecraft.curseforge.com/projects/common-capabilities - https://minecraft.curseforge.com/projects/common-capabilities/files/2315231/download

LightningCraft - https://minecraft.curseforge.com/projects/lightningcraft - https://minecraft.curseforge.com/projects/lightningcraft/files/2320515/download

Modular Systems - https://minecraft.curseforge.com/projects/modular-systems - https://minecraft.curseforge.com/projects/modular-systems/files/2323542/download

Bookshelf API Library - https://minecraft.curseforge.com/projects/bookshelf-api-library - https://minecraft.curseforge.com/projects/bookshelf-api-library/files/2320422/download

More Anvils - https://mods.curse.com/mc-mods/minecraft/243578-more-anvils - https://minecraft.curseforge.com/projects/more-anvils/files/2312132/download

NeoTech - https://minecraft.curseforge.com/projects/neotech - https://minecraft.curseforge.com/projects/neotech/files/2323429/download

Nether Essence - https://mods.curse.com/mc-mods/minecraft/238223-nether-essence - https://minecraft.curseforge.com/projects/nether-essence/files/2312138/download

Persistent Bits - https://minecraft.curseforge.com/projects/persistent-bits - https://minecraft.curseforge.com/projects/persistent-bits/files/2320914/download

Progressive Automation - https://mods.curse.com/mc-mods/minecraft/220606-progressive-automation-early-miner#t1:description - https://minecraft.curseforge.com/projects/progressive-automation-early-miner/files/2317610/download

QuantumFlux - https://mods.curse.com/mc-mods/minecraft/228609-quantumflux - https://minecraft.curseforge.com/projects/quantumflux/files/2304672/download

Structured Crafting - https://minecraft.curseforge.com/projects/structured-crafting - https://minecraft.curseforge.com/projects/structured-crafting/files/2312900/download

Tinkers' Addons - https://minecraft.curseforge.com/projects/tinkers-addons - https://minecraft.curseforge.com/projects/tinkers-addons/files/2314984/download

VeinMiner - https://minecraft.curseforge.com/projects/veinminer - https://minecraft.curseforge.com/projects/veinminer/files/2314335/download

Water Strainer - https://minecraft.curseforge.com/projects/water-strainer - https://minecraft.curseforge.com/projects/water-strainer/files/2322889/download

Ye Olde Tanks - https://minecraft.curseforge.com/projects/ye-olde-tanks - https://minecraft.curseforge.com/projects/ye-olde-tanks/files/2313525/download

**Comment by robaimes** [comment]
Added:
- Apple Skin
- Thut Core
- Thut's Elevators
- Fancy Fluid Storage
- FloodLights
- Help Fixer
- Chance Cubes

**Comment by robaimes** [comment]
Added Ender Utilities

**Comment by robaimes** [comment]
****Full list of additions from this issue:****
- Apple Skin
- Thut Core
- Thut's Elevators
- FFS
- FloodLights
- Help Fixer
- Chance Cubes (And also the streamer section)
- Ender Utilities
- Veinminer (Trees only, though!)

****Considered and acted upon in a different manner:****
- Tinkers Addons - boni, the TCon author, recently released an Iguana Tweaks style mod for 1.10 and will use that instead once in a more stable state.
- Integrated Dynamics, Energy Synergy, Common Capabilities, EZ Storage 2 - All have equivalents already in the pack already. Not added to avoid repetition and clutter.

The rest in my opinion do not fit what I am trying to achieve. (Bare in mind though, some of the mods listed, for example; Simple Harvest are a feature of other mods, in this case Agricraft. Agricraft will be added when released for 1.10)

****Other examples of equivalent mods:****
- Persistent Bits == ChickenChunks
- QuantumFlux == EnderIO / RFTools / TESLA
- NeoTech == IC2 / TESLA Essentials / Immersive Engineering / CoFH (When released)
- Ye Olde Tanks == Mekanism Tanks / TCon Tanks / ExtraUtils 2 / CoFH Tanks / Buildcraft Tanks
