### ISSUE TITLE
Mod Request Actually Additions

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#15]
i just like this mod adds lots of useful blocks and tools very handy and cool https://minecraft.curseforge.com/projects/actually-additions?gameCategorySlug=mc-mods&projectID=228404

**Comment by robaimes** [comment]
Looked at this a few times. I kind of want to add it as one of those nifty things, similar to Random Things. But, I've realised that most if not all of the features are already included in other mods in the pack, or will be included very soon. The difference with Random Things, is that it adds very interesting, obscure yet useful things such as the Player Inventory (among many other things, of course) which I've not seen any other mod include before.

For this version of DNS my aim is top reduce the amount of 'clutter' or repetition of features. (With the exclusion of IC2 / TE / Mekanism / Ender IO etc as they all use different power, mechanics and can be toned to player preference)
