### ISSUE TITLE
[Mod Request] Thut's Elevators

### ISSUE THREAD

**Issue by ChaosTherum** [DNSTechpack/DNS10-MC1.10.2#17]
Mod that adds dynamic elevators capable of up to 64 floor pretty straight forward

https://minecraft.curseforge.com/projects/thuts-elevators?gameCategorySlug=mc-mods&projectID=224375

**Comment by robaimes** [comment]
https://github.com/DNSTechpack/DNS10-MC1.10.2/blob/master/MODLIST.md

This is already in the pack.
