### ISSUE TITLE
Problem by removing "Basic Universal Cable"

### ISSUE THREAD

**Issue by Zell7288** [DNSTechpack/DNS10-MC1.10.2#19]
* **Type of issue?**
  * BUG /QUESTION
  
* **DNS Version?**
  * 10.0.0.0
  

* **What should happen?** 
  * With Wrench or Pickaxe i should be able to remove Basic Universal Cable. Instead my Client Crash.
  

* **What actually happens?**
  * Client Crashes by 9% removing Basic Universal Cable
  
* **Description?** 
  * Here is the Log:
http://paste.atlauncher.com/view/c79fb851

Hope it Helps you. Like the Modpack and Hope it will fix fast or i get Information when i have something wrong.

BR
Zell7288

**Comment by robaimes** [comment]
Thanks for the report.

There is an open issue on Mekanism's tracker regarding this issue: [HERE](https://github.com/aidancbrady/Mekanism/pull/3967)

I will keep an eye on this issue. I may be able to package the unofficial / homebaked version, (will check license later) but if not I will wait until Aidan has merged the changes.

**Comment by robaimes** [comment]
Pushing a fix in version `10.0.0.1` soon.
