### ISSUE TITLE
Mod Request

### ISSUE THREAD

**Issue by yustic** [DNSTechpack/DNS10-MC1.10.2#20]
Mod Requests:
ProjectE: https://minecraft.curseforge.com/projects/projecte

MatterOverdrive, of which I can't find a proper link, so if you could 👍

**Comment by robaimes** [comment]
Project e will be added soon. MO is not yet available for 1.10, it will be added when available.

**Comment by robaimes** [comment]
https://github.com/DNSTechpack/DNS10-MC1.10.2/commit/52d985ee54d5a801af042cf59aaff57e8a5372bd

Added to beta in preparation of 10.0.1.0
