### ISSUE TITLE
"Random Things" conflicts with Optifine

### ISSUE THREAD

**Issue by tullo-x86** [DNSTechpack/DNS10-MC1.10.2#21]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 10.0.0.1

* **Steps taken** 
  * `OptiFine 1.10.2 HD U D3` was opened and extracted. The resulting `Optifine_blah_MOD.jar` file was added to the mod list in ATLauncher, then the DNS Techpack instance was launched.
  * This process was also attempted using MultiMC with the same result.
  * This process was also attempted using `OptiFine 1.10.2 HD U D2` with the same result.
  
* **Expected result** 
  * Minecraft should successfully load with Optifine and DNS Techpack.
  
* **What actually happens?**
  * Loading failed during mod construction. 
  
* **Description?** 
  * I miss the performance boost from Optifine on my tiny li'l laptop GPU.

-----

* Crash log: http://pastebin.com/v4tFrJHr
* Forge log: (It's a client problem so no server log was generated)

**Comment by robaimes** [comment]
Please try using **[this](http://optifine.net/adloadx?f=preview_OptiFine_1.10.2_HD_U_D4_pre.jar)** version of Optifine.

**Comment by tullo-x86** [comment]
Using the preview version has the same result: http://pastebin.com/BrC3uJjq

**Comment by robaimes** [comment]
@tullo-x86 Could you update to `10.0.1.2` of DNS and try again with the D4_Pre jar?

**Comment by robaimes** [comment]
Update: I have tried myself. Using `preview_Optifine_1.10.2_HD_U_D4_pre.jar` and the latest version of DNS (`10.0.1.2`) works fine.
