### ISSUE TITLE
Adjacent doors no longer open simultaneously in 10.0.1.2

### ISSUE THREAD

**Issue by tullo-x86** [DNSTechpack/DNS10-MC1.10.2#23]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 10.0.1.2
  * Using "Recommended" mod list.
  
* **What should happen?** 
  * Right-clicking a door in the world should open both the clicked door and the matching adjacent door
  
* **What actually happens?**
  * The clicked door opens, but the adjacent door does not.
  
* **Description?** 
  * This worked in `10.0.0.1`. This bug occurs both in existing worlds created in `10.0.0.1` and new worlds created in `10.0.1.2`.

-----

* LOGS: FML displays the following line:  
`[2016/11/20 23:08:05 PM] [Client thread/INFO] [FML]: [Quark] 'Double doors open together' is forcefully disabled as it's incompatible with the following loaded mods: [malisisdoors]`

Full log: https://be-lumino.us/files/atlauncher-log-20161121-111610.txt (file too big for Pastebin)

**Comment by robaimes** [comment]
Looking at the Quark changelog:
`- Tweaks: Double Doors opening together now disables itself if Malisis' Doors is loaded.`

This issue is also on the Quark GitHub: https://github.com/Vazkii/Quark/issues/217

This is (unfortunately) an intentional change. I will however see what I can do.

**Comment by robaimes** [comment]
I have posted in the [Quark issue](https://github.com/Vazkii/Quark/issues/217#issuecomment-262011895) with some more information on this. Hopefully this will provide some insight and hopefully allow us to bring the feature back.
