### ISSUE TITLE
bug, cross mod compability mekanism reffined storage

### ISSUE THREAD

**Issue by oedbro** [DNSTechpack/DNS10-MC1.10.2#27]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 10.0.2.1
 
* **What should happen?**
    Transfering power from energy cube via universal cable to the reffined storage controller
  

* **What actually happens?**
    The controller wont accept the power
  
-----

-----

**Comment by oedbro** [comment]
It wont work on:
    * EnderIO - Cappacitor Bank
    * RFTools - Advancesd Powercell
    * Forestry - Squeezer

It will work on
    * IC2 - MFSU
    * Imersive Enginering - Cappacitor
    * Draconic Evolution - Energy Infuser
    * Extra Utilities 2 - Wireless RF Battery
    * DeepResonense - Smelter

**Comment by Alux2k** [comment]
Its the mekanism cable itself that does not seem to be converting properly.  

As a work around, use mekanism cables to an energy cube, then use enderio conduits to take the power out from the cube to the machines.

**Comment by MacDonagal** [comment]
> Its the mekanism cable itself that does not seem to be converting properly.

> As a work around, use mekanism cables to an energy cube, then use enderio conduits to take the power out from the cube to the machines.

You need to use the configurator to push/pull on energy cable. Sorry for my english, I'm a french
