### ISSUE TITLE
Mod Request - Mo'Creatures

### ISSUE THREAD

**Issue by Mothix** [DNSTechpack/DNS10-MC1.10.2#29]
MOD REQUEST
  
DNS Version - 1.10.2

Mo'Creatures;
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272337-mo-creatures-v10-0-5-with-bear-mounts

Was in the pack a few years ago but was removed due to incompatibility issues, those issues have since been fix internally and it would be great to bring it back!

**Comment by robaimes** [comment]
Unfortunately this is still a thing:

**F.A.Q.
Q.: Can I include your mod in my modpack?
A.: I'm sorry, but no. Please do not PM me about it. The answer is still no.**

So I cannot :|
