### ISSUE TITLE
MOD REQUEST

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS10-MC1.10.2#30]
MOD REQUEST
 
1.10.2
  
Cyberware:
Cyberware is a mod about augmenting the human body, inspired by cyberpunk themes and particularly influenced by Deus Ex and Shadowrun. 

https://minecraft.curseforge.com/projects/cyberware

WIRED: More Augs
A Small Companion mod for Cyberware to add in new Augments and Cyberpunk styled features.

https://minecraft.curseforge.com/projects/wired-more-augs

Simple Upgrades
Simple Upgrades is a mod that started in 1.8.9 as SimpleAddons but has evolved into a 1.9 mod. At first you think "oh it will only do simple things" but no. Simple Upgrades is adding more and more with each update.

https://mods.curse.com/mc-mods/minecraft/243166-simple-upgrades

**Comment by robaimes** [comment]
Forgot about this one. not adding these sorry. Cyberware is too close to matter overdrive which I feel is the superior mod. (It's now updated and will be added shortly after testing etc)
