### ISSUE TITLE
MOD REQUEST-Architecturecraft

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS10-MC1.10.2#32]
MOD
  
1.10.2

architecturecraft
https://minecraft.curseforge.com/projects/architecturecraft
Adds blocks for building.

**Comment by robaimes** [comment]
Looks good. Will add it once I have my PC back and can test.

**Comment by robaimes** [comment]
Added as of version `10.0.8.0` : https://github.com/DNSTechpack/DNS10-MC1.10.2/commit/74c0a0dc896d9583a24be56b8fdfd2da4af9b359
