### ISSUE TITLE
Mod Removal Request.

### ISSUE THREAD

**Issue by GldnSabre74** [DNSTechpack/DNS10-MC1.10.2#36]
MOD Removal REQUEST 
  
  * 10.0.3.0
 Please Remove IC2 as it is an old mod and no one hardly uses it anymore and there are 3 different mods that handle its purpose. Also this request for removal is due to Refined Storage patterns being made with the Mekanism recipes and them being replaced with IC2 items.

Thank You.

**Comment by robaimes** [comment]
The recipe can be fixed. I'll run a poll on Discord and Twitter to see what people think of removing.

**Comment by Alux2k** [comment]
If your voting to remove mods then Railcraft would be a better vote... Atm Railcraft neither has boilers or tanks its only use is if you want to build a fancy rail system.
