### ISSUE TITLE
MOD REQUEST - Decocraft2

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS10-MC1.10.2#37]
MOD REQUEST
  
1.10.2

Decocraft2
https://minecraft.curseforge.com/projects/decocraft2

**Comment by robaimes** [comment]
Again not a default mod, however putting this in a `Cosmetic` optional category would not be out of the question. Will set this up once PC is back.

**Comment by robaimes** [comment]
Added as of version **10.1.0.0**
