### ISSUE TITLE
BUG - /help in SSP causing crash

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS10-MC1.10.2#40]
BUG

10.0.4.1
  
When using /help in SSP the game crashes.  

As soon as /help is entered the help dialogue appears in chat followed by an immediate crash.

-----

* Crash log:
[crash-2017-01-02_20.51.26-server.txt](https://github.com/DNSTechpack/DNS10-MC1.10.2/files/681373/crash-2017-01-02_20.51.26-server.txt)

[crash-2017-01-02_21.48.07-server.txt](https://github.com/DNSTechpack/DNS10-MC1.10.2/files/681414/crash-2017-01-02_21.48.07-server.txt)

* Forge log:

**Comment by robaimes** [comment]
Can you upload a couple of other logs from when this occurs? I want to make sure that the same stacktrace is in each.

**Comment by Svish** [comment]
Have you tried adding the [HelpFixer](https://minecraft.curseforge.com/projects/helpfixer?gameCategorySlug=mc-mods&projectID=223797) mod? Don't remember the crash I had, but I had issues with `/help` in a different pack, and adding that mod fixed it...

(haven't tried this mod-pack yet, but planning to 😛 )

**Comment by robaimes** [comment]
We already have the mod @Svish - Issue is old now, may not still be a thing. Not had any other reports of this happening so either nobody uses `/help` or it's alright now.

**Comment by Svish** [comment]
Ah, nevermind me then 😛 (maybe close the issue?)
