### ISSUE TITLE
Mod Request Applied Energistics 2

### ISSUE THREAD

**Issue by Marker248** [DNSTechpack/DNS10-MC1.10.2#41]
MOD REQUEST
  
* **DNS Version?**
  * 10.0.4.2
  
I simply love this mod. It's been an integral part of DNS for many versions and now that it is actively updated by another team there is a version compatible with 1.10.2. I have even loaded it on a single player world with DNS 10.0.2.0 with no issues. I dont imagine a server would have many issue with it either. 
There are other mod packs out there that already load both AE2 and refined storage in the same pack as well so they do work side by side.

**Comment by robaimes** [comment]
For the moment in leaving it out due to the impact it has on servers. I will be adding it later though.

**Comment by Lazarix** [comment]
Hi @iamomicron, which issues need to be resolved before considering it for addition?
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues

**Comment by robaimes** [comment]
It's more about the impact it has on servers, not bugs. Unless things have drastically changed, large ME systems cause huge lag issues for servers, especially when there are multiple networks.

As I said though, it will be added at some point. For now, I don't have a PC and am working from a laptop which cannot run DNS effectively. I cannot therefore test new mods, so I will only add new mods once I have the means to thoroughly test them.

**Comment by Marker248** [comment]
I have a rather large system on my current server. 1.7.10 and I have been constantly checking the tps which never goes below 18.5
That being said I don't know if there are changes to the code in 1.10.2 or not if anything I understand it's all client side rendering that cause most of the lag. (My fps suffers)


-------- Original message --------

**Comment by Lazarix** [comment]
I'll happily replicate the server and test the client with a large ME system if you'd like to, understand you're unable to at the moment.
Let me know and i'll help if you'd like.

**Comment by Yoosk** [comment]
So, with large RS system there seems to be multiple issues, as we made one on official server. Everything breaks, server crashes due to importers, auto-crafting gets stuck every time and items vanish nowhere to be seen.
We really need to switch to something better.

**Comment by robaimes** [comment]
Just to update - Will probably add AE2 as an optional mod along with RS. ***But*** I will probably only allow installation of 1 mod. So either you have AE2 *or* RS, not both. As far as I see it, it would just cause confusion. If anyone has any reasons to why this shouldn't be done then let me know!

Keeping open for now until change is pushed.

**Comment by robaimes** [comment]
AE2 is now an optional mod. For now it can be installed alongside RS but that will probably change in the future. This is to allow people to migrate their RS systems over to AE2 if they wish to.

**Comment by Marker248** [comment]
A solid plan actually. RS is simpler than AE2 so it makes sense.

-------- Original message --------

**Comment by Yoosk** [comment]
But ae2 even at this state is more stable than RS in any way, it should be the other way.

**Comment by robaimes** [comment]
People have already established rs systems. This way they can switch if
they wish to. Both can be installed simultaneously for now. When some time
passes this will change and we will discuss this again.
