### ISSUE TITLE
MOD REQUEST (Carpenter's Blocks)

### ISSUE THREAD

**Issue by endean82** [DNSTechpack/DNS10-MC1.10.2#47]
* **Type of issue?**
  * MOD REQUEST
  
* **DNS Version?**
  * 10.0.0.0
  

-----

Any other info?
I know this one is still being updated, but I absolutely love this mod! If not now definitely when it gets more work done on it.

**Comment by robaimes** [comment]
This mod is still not released. And yes, it will be added **if** it does get released, as it was part of the previous pack.
