### ISSUE TITLE
JurassiCraft

### ISSUE THREAD

**Issue by Xyain** [DNSTechpack/DNS10-MC1.10.2#5]
I'd request JurassiCraft, its a lot of fun, even if its optional...

**Comment by robaimes** [comment]
Jurassicraft is not a mod I wish to add to DNS. The pack is kitchen sink with heavy focus on technology and automation.

The reason I do not want to add this is because it's primary focus is on exploration and combat. I do not believe mixing hard mobs and in a tech pack is a wise idea.
