### ISSUE TITLE
MOD REQUEST - Multiple

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS10-MC1.10.2#51]
Server:
-------
Travel Huts
https://minecraft.curseforge.com/projects/travel-huts

Bedrock B Gone
https://minecraft.curseforge.com/projects/bedrock-b-gone

SilentBoss
https://minecraft.curseforge.com/projects/silentboss

DebugServerInfo (also works on smp)
https://mods.curse.com/mc-mods/minecraft/256400-debugserverinfo

Magic:
-------
Botania addon:
BotaniaVisualizer
https://mods.curse.com/mc-mods/minecraft/260616-botaniavisualizer

Blood magic addon:
Animus
https://mods.curse.com/mc-mods/minecraft/229664-animus

Vitality
https://mods.curse.com/mc-mods/minecraft/253721-vitality

Animunda:Black Arts Of The Void
https://minecraft.curseforge.com/projects/animunda-black-arts-of-the-void

PhiloStone
https://minecraft.curseforge.com/projects/philostone.

Sanguimancy
https://minecraft.curseforge.com/projects/sanguimancy

Roots
https://mods.curse.com/mc-mods/minecraft/246183-roots

Dragon mounts
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1439594-dragon-mounts-r46-wip

Vampirism - Become a vampire!
https://mods.curse.com/mc-mods/minecraft/233029-vampirism-become-a-vampire

Ars magica 2
https://github.com/Growlith1223/ArsMagica2

Mystical agriculture
https://mods.curse.com/mc-mods/minecraft/246640-mystical-agriculture

Tech:
-----
Tinker's construct addons:
Tinkers' tool leveling
https://mods.curse.com/mc-mods/minecraft/250957-tinkers-tool-leveling

Simple Sirens, Alarms, and Bells
https://minecraft.curseforge.com/projects/simple-sirens-alarms-and-bells

Tri-Sabers
https://minecraft.curseforge.com/projects/tri-sabers

OpenModularTurrets
https://minecraft.curseforge.com/projects/openmodularturrets

Open Modular Passive Defense
https://minecraft.curseforge.com/projects/open-modular-passive-defense

Redstone Paste
https://minecraft.curseforge.com/projects/redstone-paste

QuantumFlux
https://minecraft.curseforge.com/projects/quantumflux

Actually Additions
https://mods.curse.com/mc-mods/minecraft/228404-actually-additions

Woot
https://mods.curse.com/mc-mods/minecraft/244049-woot

Speedster Heroes
https://mods.curse.com/mc-mods/minecraft/252318-speedster-heroes

Crossroads MC
https://mods.curse.com/mc-mods/minecraft/250231-crossroads-mc

Dooglamoo cities
https://mods.curse.com/mc-mods/minecraft/250834-dooglamoo-cities

Refined Exchange
https://mods.curse.com/mc-mods/minecraft/260343-refined-exchange

Tiny progressions
https://mods.curse.com/mc-mods/minecraft/250850-tiny-progressions

Robe Bridge Mod
https://mods.curse.com/mc-mods/minecraft/238050-rope-bridge-mod

Scanner
https://mods.curse.com/mc-mods/minecraft/250833-scanner

Aesthetics / Building:
-----------------------
Rustic
https://minecraft.curseforge.com/projects/rustic

Rockhounding Mod: Surface
https://minecraft.curseforge.com/projects/rockhounding-mod-surface

Earthworks
https://minecraft.curseforge.com/projects/earthworks

Storage Drawers Extras
https://minecraft.curseforge.com/projects/storage-drawers-extras

Platforms
https://minecraft.curseforge.com/projects/platforms

Missing pieces
https://mods.curse.com/mc-mods/minecraft/236199-missing-pieces

Fence overhaul
https://minecraft.curseforge.com/projects/fence-overhaul

Prefab
https://mods.curse.com/mc-mods/minecraft/246550-prefab

General:
---------
Mo'Stuff
https://minecraft.curseforge.com/projects/mostuff

Tinkers' Tool Leveling
https://minecraft.curseforge.com/projects/tinkers-tool-leveling

More Bees
https://minecraft.curseforge.com/projects/more-bees

Colossal chests
https://minecraft.curseforge.com/projects/colossal-chests

Iron backpacks
https://minecraft.curseforge.com/projects/iron-backpacks

Kleeslabs
https://minecraft.curseforge.com/projects/kleeslabs

Cooking for blockheads
https://mods.curse.com/mc-mods/minecraft/231484-cooking-for-blockheads

Avaritia
https://mods.curse.com/mc-mods/minecraft/233785-avaritia

Avaritia addons
https://mods.curse.com/mc-mods/minecraft/248873-avaritiaddons

Clumps
https://mods.curse.com/mc-mods/minecraft/256717-clumps

WTF's Expedition: CaveBiomes, Ores, Trees, and Tweaks
https://mods.curse.com/mc-mods/minecraft/227931-wtfs-expedition-cavebiomes-ores-trees-and-tweaks

Weather, Storms, & Tornadoes
https://mods.curse.com/mc-mods/minecraft/237746-weather-storms-tornadoes

**Comment by Feez2403** [comment]
Seems good ! I hope most of these mods will be added, they all look great.
Right now, I think that there is not a lot of magic mods. With those you sent us, this could be fixed :D

**Comment by robaimes** [comment]
This is the current list of mod considerations I have, based on this post and a couple others:

General:
---------

**_More Bees_** - https://minecraft.curseforge.com/projects/more-bees/files/2326123
**_Earthworks_** - https://minecraft.curseforge.com/projects/earthworks
**_ArchitectureCraft_** - https://minecraft.curseforge.com/projects/architecturecraft
**_DecoCraft_** - https://minecraft.curseforge.com/projects/decocraft2
**_Storage Drawers Extras_** - https://minecraft.curseforge.com/projects/storage-drawers-extras
**_Iron Backpacks_** - https://minecraft.curseforge.com/projects/iron-backpacks
**_Cooking For Blockheads_** - https://minecraft.curseforge.com/projects/cooking-for-blockheads
**_Redstone Paste_** - https://minecraft.curseforge.com/projects/redstone-paste
**_Clarity_** - https://minecraft.curseforge.com/projects/clarity

Magic:
-------

**_Magical Crops Clone_** - https://mods.curse.com/mc-mods/minecraft/246640-mystical-agriculture
**_Animus_** - https://minecraft.curseforge.com/projects/animus
**_Ars Magicka 2_** - https://github.com/Growlith1223/ArsMagica2
**_Roots_** - https://minecraft.curseforge.com/projects/roots
**_Embers_** - https://minecraft.curseforge.com/projects/embers

Magic mods would all be optional. Most / all of the General mods would likely be default, except for Decocraft.

**Comment by robaimes** [comment]
Closing this as I have added what I would like to as of version 10.1.0.0. Make another issue for each mod if you really want me to reconsider.
