### ISSUE TITLE
Mod Request/ Mowzie's mobs

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#53]
* **Type of issue?**
MOD REQUEST
  
* **DNS Version?**
  * 10.0.5.0
  
Mowzie's mobs, These are without a doubt the best mobs. albeit only a few. going between the models and the drops i love it 
https://mods.curse.com/mc-mods/minecraft/250498-mowzies-mobs 

Earthworks, this is a purely decorative mod i just like the way it looks. thought you might too.
https://minecraft.curseforge.com/projects/earthworks

-----

that's all i got so far. it's a pretty damn good mod pack as it is 
Any other info?

**Comment by robaimes** [comment]
Mod mobs aren't a great fit for the pack really. It's not survival-esque. I get that it adds some discovery too, but again that isn't the main idea for the pack. Going to say no to this, but you can always add it yourself of course.

Earthworks I am considering and has been mentioned over at #51 so closing this for cleanliness.
