### ISSUE TITLE
Thermal Foundations ore do not work 

### ISSUE THREAD

**Issue by DirkSch** [DNSTechpack/DNS10-MC1.10.2#56]
* **Type of issue?**
  * BUG / CONFIG
  
* **DNS Version?**
  * 10.0.6.0
  
* **Description?** 
After Update to the new Version with Thermal Foundations ore I have made a retrogen in my old world.
al ore from Thermal Foundation can't made only smelting in a furnace. No work in Tinker smeltery, SAG Mill EnderIO ore crucher from Mekanism or IE.

**Comment by robaimes** [comment]
So the ore spawns but you can't use it in machines? Can you give me a screenshot of an example?

**Comment by robaimes** [comment]
Update: https://github.com/CoFH/Feedback/issues/37

Looks like some form of TiC compatibility issue is known. It also may be dependent on the ore or material you are aiming to smelt. I tested a few things and found that the smeltery amount most other things are working as intended.

**Working:**
* IC2 macerator
* Ender IO SAG Mill
* Thermal Expansion machines
* Actually Additions crusher
* Immersive Engineering crusher
* Tinkers' Construct smeltery
* Mekanism enriching factory

[Here's an image of them working with the smeltery](http://img.aimes.eu/2017-03-06_17-01-27.png)

So I can't replicate exactly what you are describing. What ores were you using? Please reopen the issue if you can provide more info.

**Comment by KingLemming** [comment]
There's no TiC compatibility issue - the issue as opened on our tracker is for us to add tool metals. Ores and metal blocks work *fine*.

**Comment by DirkSch** [comment]
I think it's a JEI problem. Ores work fine but JEI can't show it.

**Comment by robaimes** [comment]
@KingLemming Ah, ok. Thanks for clarifying. The wording threw me off.
