### ISSUE TITLE
Missing lots of block textures from the new thermal expansion add.

### ISSUE THREAD

**Issue by minecraftuser1243** [DNSTechpack/DNS10-MC1.10.2#58]
BUG

Version 
10.0.6.2

All of these textures are missing for some reason. Its related to the dns pack specifically because I posted it on the github for thermal expansion and no one else had this problem.

<img width="1440" alt="screen shot 2017-03-06 at 3 17 27 pm" 
src="https://cloud.githubusercontent.com/assets/26193542/23634649/36ceff44-0280-11e7-959a-fc540fde383c.png">
<img width="656" alt="screen shot 2017-03-06 at 3 16 58 pm" src="https://cloud.githubusercontent.com/assets/26193542/23634652/3819968e-0280-11e7-8e46-b3c3b7fbf0d9.png">
<img width="1440" alt="screen shot 2017-03-06 at 3 18 30 pm" src="https://cloud.githubusercontent.com/assets/26193542/23634653/38cfde12-0280-11e7-955f-a128ce069236.png">
<img width="1440" alt="screen shot 2017-03-06 at 3 18 13 pm" src="https://cloud.githubusercontent.com/assets/26193542/23634654/39770886-0280-11e7-8536-24885dd389da.png">

**Comment by robaimes** [comment]
I can't reproduce this error. Have you installed additional mods? Optifine maybe?

![Image](http://img.aimes.eu/2017-03-06_23-32-20.png)

**Comment by minecraftuser1243** [comment]
I literally downloaded the new pack and played it and this is what happened.

**Comment by minecraftuser1243** [comment]
i have journey map, ae2, blood magic, rarmor, botania, magneticraft, refined storage, rftools dimensions, steves carts 2, steves factory manager, natura, pams, mouse tweaks and project e all installed from the additional mods tab when you install a new instance.

**Comment by minecraftuser1243** [comment]
Maybe it has to do with a certain java version? im cleanly installing atlauncher now to see if it works.

**Comment by minecraftuser1243** [comment]
I figured it out, i read on the origianl thread i posted about this and someone said that osx is the problem. so ill just deal with it!

**Comment by robaimes** [comment]
What thread? Any context?

**Comment by minecraftuser1243** [comment]
https://github.com/CoFH/Feedback/issues/6

**Comment by robaimes** [comment]
Brilliant, thank you.

**Comment by minecraftuser1243** [comment]
sure, so i guess theres nothing i can do then right?

**Comment by robaimes** [comment]
Doesn't look like it right now. Until someone tracks down the cause. Wish I
could say otherwise :/

I will try to find out more

**Comment by minecraftuser1243** [comment]
ok thank you so much! For some strange reason it worked just fine in the curse launcher with thermal expansion installed, no missing textures, but didnt work in the dns. not sure why
