### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#59]
* **Type of issue?**
  * BUG /
  
* **DNS Version?**
  * 10.0.6.2
  
Insta Ctd when trying to open current world. after last update
  

  
* **Description?** 
  * Using Item X should open Y interface but, when the item is used in the hand, the client crashes.

-----

* Crash log: http://pastebin.com/GimcXDD7

-----

something to do with sonar core or calculator maybe, i tried removing some of the blocks e.g. flawless greenhouse.

**Comment by trechetican** [comment]
okay done more testing seems like the Flux networks is causing problems i removed the mod and it worked. i then re-installed the mod. okay it's fine until i try placing any of the power blocks. the controller works fine though

**Comment by robaimes** [comment]
Judging by the log it's something you have connected to an Ender IO machine. I don't know if Ender IO is receiving the power or sending it though.

**Comment by trechetican** [comment]
it seams to be the flux points and flux plugs trying to send and or receive power on the ender io capacitor

**Comment by robaimes** [comment]
There was a Flux Networks update yesterday that has the changelog `Fixed various crashes` so hopefully this should be a remedy to this.

Will include in update later today.

**Comment by trechetican** [comment]
just tested it quickly and it does seem to have fixed my issue at least

**Comment by robaimes** [comment]
Awesome, thanks. Closing this for now, but reopen if it persists :)
