### ISSUE TITLE
Client can not connect to a server - IC2:sapling has been registered twice

### ISSUE THREAD

**Issue by FSDel** [DNSTechpack/DNS10-MC1.10.2#60]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 10.0.6.0 - 10.0.6.2
  
* **What should happen?** 
 Client should be able to connect to the server

* **What actually happens?**
Client receives the following errors:
On First Attempt to log in:
 ![firstattempterror](https://cloud.githubusercontent.com/assets/26369512/23837953/4f2c5096-07e4-11e7-9364-387658ce01ad.PNG)

After the first attempt, this error will be provided in future attempts:

![error](https://cloud.githubusercontent.com/assets/26369512/23837960/629b61d0-07e4-11e7-9d9c-9c896a311be3.PNG)

-----

Forge Log:
[fml-server-latest.txt](https://github.com/DNSTechpack/DNS10-MC1.10.2/files/837051/fml-server-latest.txt)

-----
Issue appears to only affect people randomly. Some people report hosting servers fine.

Not sure if it's related, but i did have to confirm the following:
[11:54:28] [Server thread/WARN] [FML/]: Forge Mod Loader detected that the backup level.dat is being used.

**Comment by FSDel** [comment]
Issue does not occur in 10.0.5.0
occurs in 10.0.6.0 - 10.0.6.2

Removal of IC2 and dependant mods will remove the issue.

**Comment by robaimes** [comment]
@FSDel Me and COL tested and we believe the addition Actually Additions may be the root cause of this. Can you try remove AA and see if the issue disappears?

Edit: daiirik also tested and seems to have fixed for him too. If you can confirm I will try to seek help with the AA dev.

**Comment by robaimes** [comment]
Confirmed by another user havng the same issue: https://minecraft.curseforge.com/projects/actually-additions?comment=379

Apparently it's a Forge bug, though.

**Comment by FSDel** [comment]
Issue did not occur after the removal of Actually Additions.

Worth mentioning that adding Actually Additions back into my server after World generation, and the issue did not start reoccurring...

I'm unsure if the mod is usable however, as maybe it has worldgen items that would be missing.

**Comment by FSDel** [comment]
I have been playing since re-adding Actually Additions, having restarted the server several times ( Especially after first visiting the Nether )

Adding the mod back in after world generation seems to be a viable work-around.

**Comment by robaimes** [comment]
It is indeed a workaround, but not something I wish to ship as the only way to play. Not everyone gets the error and such but it's not the ideal way to play :(

I will see if I can find other ways to go around this.

**Comment by robaimes** [comment]
Temporary solution, AA has been moved to optional and listed as 'Not recommended'. So, *if* you get this error, you can just simply remove and reinstall with ease.
