### ISSUE TITLE
OpenComputers Diamond Chips Recipe Conflict with Thermal Foundation

### ISSUE THREAD

**Issue by FSDel** [DNSTechpack/DNS10-MC1.10.2#62]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 10.0.7.0
  
* **What should happen?** 
  1 diamond should make 6 diamond chips
  

* **What actually happens?**
  Diamond Nuggets from Thermal Foundation are created instead, can not be used as chips.
  
-----

**Comment by drakkillen** [comment]
Idea to IAmOmicron: have it so nuggets and chips can be crafted by each other,
nugget>chip, chip>nugget

**Comment by robaimes** [comment]
I already said that was what I'm going to do. Unless we take the easy way
or and use the no more recipe conflict mod

**Comment by robaimes** [comment]
Recipe changed. You would now get 9 chips from a diamond to make it consistent with nuggets if using some form of autocrafter like AE2.

To craft them normally you will need to use the new shapeless recipe. 

`1x Diamond Nugget` = `1x Diamond Chip`

This recipe can be reversed to aquire some diamond nuggets.
