### ISSUE TITLE
MOD REQUES

### ISSUE THREAD

**Issue by drakkillen** [DNSTechpack/DNS10-MC1.10.2#65]
MOD REQUEST RefinedStorage add-on 
* **DNS Version?**
  * 10.0.8.1
  
https://minecraft.curseforge.com/projects/rebornstorage

* **Description?** 
A addon mod for refined storage that adds the autocrafting multiblock functionality from AE1

**Comment by robaimes** [comment]
Seeing as the you have the option to use AE2 or RS I don't think this is very necessary. There are other forms of autocrafting available. RS is meant to be the *lightweight* alternative to AE, so I'd prefer to keep it like that.
