### ISSUE TITLE
Portal Mod Request

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#66]
* **Type of issue?**
   MOD REQUEST
  

  
https://minecraft.curseforge.com/projects/portal-gun 

Portal mod from ichun as wel all know and love. i did read there is a server problem buuut it's a cool mod

-----

-----

Any other info?

**Comment by robaimes** [comment]
Will test / add when I'm back at University and when I have time to update. Have exams 1st week back and a bunch of deadlines the same week.

**Comment by trechetican** [comment]
no rush.

**Comment by robaimes** [comment]
Added in 10.0.9.0
