### ISSUE TITLE
Mod request

### ISSUE THREAD

**Issue by LeDieuJojo** [DNSTechpack/DNS10-MC1.10.2#69]
MOD REQUEST

Not yet available in 1.10.2 but please add it when it will be possible.

Quarryplus: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288467-active-1-7-10-ssp-smp-forge-yogpstops-mods

**Comment by robaimes** [comment]
Please refrain from creating mod requests for mods that are not yet released.

The general rule for this, is that if the mod was in the 1.7.10 version of DNS it will most likely be added when they are released.
