### ISSUE TITLE
Crash [7.8.11.1]

### ISSUE THREAD

**Issue by Migmag789** [DNSTechpack/DNS10-MC1.10.2#70]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 7.8.11.1
  
I don't know the crash reason.

-----

Thanks tell me about there :)
[crash-2017-05-11_21.29.57-client.txt](https://github.com/DNSTechpack/DNS10-MC1.10.2/files/999480/crash-2017-05-11_21.29.57-client.txt)

**Comment by robaimes** [comment]
The crash is to do with ProjectE recipe handler in NEI, but I cannot provide support for Minecraft 1.7.10 as it is end-of-life. Even if I was providing support, the mods have not updated, meaning the crash still exists.

You'll have to try removing Project E.

**Comment by Migmag789** [comment]
Okay, thanks. Maybe it's my script? I just deleted the "ProjectE" part of the script. Because before that did not crash ...

**Comment by robaimes** [comment]
What script? Could you elaborate, or paste it here?

**Comment by Migmag789** [comment]
Okay :
#by Migmag789
#little tweaks

#craftable diamond
recipes.addShaped(<minecraft:diamond> * 3, [[null, <ore:crystalCertusQuartz>, null], [<ore:crystalCertusQuartz>, <ore:ingotPlatinum>, <ore:crystalCertusQuartz>], [null, <ore:crystalCertusQuartz>, null]]);

#philosopher stone's dirty dig
recipes.addShaped(<ProjectE:item.pe_philosophers_stone>, [[<ore:compressedDirt1x>, <ore:compressedDirt1x>]]);

#steel production
recipes.addShaped(<usefulDNS:RawSteel>, [[<ore:coal>, <ore:ingotIron>]]);

#easy & peaceful string
recipes.addShaped(<minecraft:string> * 4, [[<minecraft:stick>, <minecraft:wool>]]);

**Comment by robaimes** [comment]
```
#philosopher stone's dirty dig
recipes.addShaped(ProjectE:item.pe_philosophers_stone, [[ore:compressedDirt1x, ore:compressedDirt1x]]);
```

Of any this is likely the cause, but can't be sure.

**Comment by Migmag789** [comment]
Oh no i have removed projectE... XD
I'm going to test :D Thanks
