### ISSUE TITLE
MOD REQUEST - Reborn Storage

### ISSUE THREAD

**Issue by TRUNKSNEO** [DNSTechpack/DNS10-MC1.10.2#85]
MOD REQUEST - Add Reborn Storage
  
* **DNS Version?**
DNS Techpack 10.x.x.x/lates (10.3.0.5)
  

* **Description?** 
Please consider adding this mod to DNS Techpack 10-MC1.10.2 has it would help with storage capacity in particularity liquid storage capacity and would eliminate the need to have more pipes running, just  to have external capacity like drums, etc.
Thank you. 

Any other info?
Link:
https://minecraft.curseforge.com/projects/rebornstorage

thank you for your time,
TrunksNeo

**Comment by Madcock83** [comment]
Kinda don't believe we don't have it already.  Not sure we will be doing much updating to 1.10. But we'll have a look.

**Comment by TRUNKSNEO** [comment]
Master Madcock83 thank your for your feedback. I understand the point of being and update for older version but really appreciate it. I will not nag more about 1.10 after finishing the Lets Play series I started on 1.10 version... dam me :p



no really thank you for your time,
TrunksNeo

**Comment by Madcock83** [comment]
I'm not above doing an update for 1.10.  I think it's still played a good bit.  Could not hurt to take a look at it.

**Comment by TRUNKSNEO** [comment]
Quick update on this request I forgot to add the rest of the addons links:
https://minecraft.curseforge.com/projects/refined-storage-addons


Thank you once again ;)
 
edit: just seen its not available for MC 1.10 done request see if its possible, fingers x

**Comment by TRUNKSNEO** [comment]
Hey mister you can go ahead and close this request please not available to 1.10 and not update coming ;-( 
I will try and close this my self. 
Thank you for the inputs.
